name: Update locales
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - app/src/main/res/values/settings.xml
jobs:
  update-locales:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update locales
      run: .scripts/locales.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: "Update locales"
        commit-message: "Update locales"
        branch-suffix: timestamp
